/** Required package class namespace */
package recipebook;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.event.WindowListener;
import javax.swing.JOptionPane;
import tools.Image;
import recipebook.LocationMethods;


/** 
* StartMenu.java - A menu which welcomes the user.
*
* @author Marissa Rowles
* @teacher Mr. Wachs 
* @since 26-Oct-2021 
*/
public class StartMenu extends JFrame {

    String image = "/media/TheFridge.png";
    public static ImageIcon icon;
    
    /**
     * Default constructor, set class properties
     */
    public StartMenu (){
        //setImage();
        initComponents();
         
        // set UI properties
        this.setSize(400,225);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        setTitle("The Kitchen");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        instatiation();
        buttonSetUp("Start", btnStart, 50);
        buttonSetUp("Exit", btnExit, 100);
        objectSetUp(); 
        pack();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void instatiation() {
        btnStart       = new javax.swing.JButton();
        btnExit        = new javax.swing.JButton();
        lblTitle       = new javax.swing.JLabel();
        lblBackground  = new javax.swing.JLabel();
    }
    
    /**
     * Sets up a button
     * 
     * @param text the text that the button will read
     * @param button which button instance is being used
     * @param x the location of the button on the X-axis
     * @param y the location of the button on the Y-axis
     */
    private void buttonSetUp(String text, JButton button, int y) {
        button.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        button.setFocusPainted(false);
        button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button.setForeground(new java.awt.Color(0, 0, 0));
        button.setText(text);
        button.setBounds(255, y, 100, 30);
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (text.equals("Start")) startButton();
                else System.exit(0);
            }
        });
        
        getContentPane().add(button);
    }
    
    /**
     * Sets up the objects inside the jframe
     */
    private void objectSetUp() {
        lblTitle.setBounds(25, 23, 180, 140);
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        lblTitle.setOpaque(true);
        lblTitle.setForeground(Color.WHITE);
        lblTitle.setBackground(Color.BLACK);
        lblTitle.setText(
                "<html> <p style=\"text-align:center\">KITCHEN TIME</p>");
        getContentPane().add(lblTitle);
        
        lblBackground.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/media/gameBG.jpg")));
        lblBackground.setBounds(0, 0, 400, 225);
        getContentPane().add(lblBackground);
    }
    
    /**
     * sets an image of an object
     */
    void setImage(){
        Image images = new Image();
        icon         = images.setImage(image);
    }
    
    /**
     * disposes of the JFrame, then asks the user which 
     * recipe they want to make
     */
    void startButton(){
        this.dispose();
        LocationMethods.makeWhat();
    }
    
    // Variables declaration - do not modify
    private JButton btnStart;
    private JButton btnExit;
    private JLabel lblTitle;
    private JLabel lblBackground;
    // End of variables declaration
}
