package recipebook;

import java.awt.Dimension;
import java.awt.Frame;
import javax.swing.JDialog;

/**
 * Outputs the recipe into a JDialog
 * @author m.rowles
 */
public class OutputRecipeJDialog extends JDialog {
    
    private String recipe;
    private Dimension size;
    private boolean original;

    /**
     * Creates new form OutputRecipeJDialog
     */
    public OutputRecipeJDialog(Frame parent, boolean modal, boolean original, 
                               String text, int width, int height) {
        super(parent, modal);
        this.original = original;
        recipe = text;
        size = new Dimension(width, height);
        initComponents();
        //setSize(new Dimension(593, 476));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        recipeScroll = new javax.swing.JScrollPane();
        recipeTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("The Kitchen");
        setPreferredSize(new java.awt.Dimension(593, 506));
        setResizable(false);
        setSize(new java.awt.Dimension(593, 506));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        bgPanel.setMinimumSize(new java.awt.Dimension(593, 506));
        bgPanel.setPreferredSize(new java.awt.Dimension(593, 506));

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/tray.png"))); // NOI18N

        okButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.background"));
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        recipeScroll.setBackground(javax.swing.UIManager.getDefaults().getColor("ScrollBar.background"));
        recipeScroll.setMaximumSize(new java.awt.Dimension(460, 32767));

        recipeTextPane.setEditable(isEditable());
        recipeTextPane.setContentType("text/html"); // NOI18N
        recipeTextPane.setText("<html><body style=\"font-family:Segoe UI\">" + recipe + "</body></html>");
        recipeTextPane.setMaximumSize(new java.awt.Dimension(232, 2147483647));
        recipeTextPane.setPreferredSize(new java.awt.Dimension(232, 84));
        recipeScroll.setViewportView(recipeTextPane);

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(iconLabel)
                        .addGap(16, 16, 16)
                        .addComponent(recipeScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recipeScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(bgPanel);
        bgPanel.setBounds(0, 0, 593, 506);
        initializeContainer();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the frame
     * 
     * @param evt The button was clicked
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Ask the user if they would like to re-run the program before closing it.
     * 
     * @param evt The window has closed
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Globals.restartProgram();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JScrollPane recipeScroll;
    private javax.swing.JTextPane recipeTextPane;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Sets the properties of this form 
     * that was unable to be added to initComponents()
     */
    private void initializeContainer() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    /**
     * Checks if the recipe is an original recipe as to prevent plagarism.
     * 
     * @return if the recipe is original, return true, otherwise return false.
     */
    private boolean isEditable(){
        if (original){
            return true;
        }
        return false;
    }
}